# Form implementation generated from reading ui file 'TechAnalyze.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from View.v_MplWidget_6 import MplWidget
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_From_TechAnalyze(object):
    def setupUi(self, From_TechAnalyze):
        From_TechAnalyze.setObjectName("From_TechAnalyze")
        From_TechAnalyze.resize(1500, 500)
        From_TechAnalyze.setMinimumSize(QtCore.QSize(500, 500))
        self.gridLayout = QtWidgets.QGridLayout(From_TechAnalyze)
        self.gridLayout.setObjectName("gridLayout")
        self.lw_LayersVisitable = QtWidgets.QListWidget(
            parent=From_TechAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lw_LayersVisitable.sizePolicy().hasHeightForWidth())
        self.lw_LayersVisitable.setSizePolicy(sizePolicy)
        self.lw_LayersVisitable.setObjectName("lw_LayersVisitable")
        self.gridLayout.addWidget(self.lw_LayersVisitable, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lab_StockID = QtWidgets.QLabel(parent=From_TechAnalyze)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lab_StockID.setFont(font)
        self.lab_StockID.setObjectName("lab_StockID")
        self.horizontalLayout.addWidget(self.lab_StockID)
        self.line_StockID = QtWidgets.QLineEdit(parent=From_TechAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.line_StockID.sizePolicy().hasHeightForWidth())
        self.line_StockID.setSizePolicy(sizePolicy)
        self.line_StockID.setObjectName("line_StockID")
        self.horizontalLayout.addWidget(self.line_StockID)
        self.lab_FromDate = QtWidgets.QLabel(parent=From_TechAnalyze)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lab_FromDate.setFont(font)
        self.lab_FromDate.setObjectName("lab_FromDate")
        self.horizontalLayout.addWidget(self.lab_FromDate)
        self.de_FromDate = QtWidgets.QDateEdit(parent=From_TechAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.de_FromDate.sizePolicy().hasHeightForWidth())
        self.de_FromDate.setSizePolicy(sizePolicy)
        self.de_FromDate.setObjectName("de_FromDate")
        self.horizontalLayout.addWidget(self.de_FromDate)
        self.lab_ToDate = QtWidgets.QLabel(parent=From_TechAnalyze)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lab_ToDate.setFont(font)
        self.lab_ToDate.setObjectName("lab_ToDate")
        self.horizontalLayout.addWidget(self.lab_ToDate)
        self.de_ToDate = QtWidgets.QDateEdit(parent=From_TechAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.de_ToDate.sizePolicy().hasHeightForWidth())
        self.de_ToDate.setSizePolicy(sizePolicy)
        self.de_ToDate.setObjectName("de_ToDate")
        self.horizontalLayout.addWidget(self.de_ToDate)
        self.pb_Query = QtWidgets.QPushButton(parent=From_TechAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pb_Query.sizePolicy().hasHeightForWidth())
        self.pb_Query.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pb_Query.setFont(font)
        self.pb_Query.setObjectName("pb_Query")
        self.horizontalLayout.addWidget(self.pb_Query)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.pb_Reflash = QtWidgets.QPushButton(parent=From_TechAnalyze)
        self.pb_Reflash.setObjectName("pb_Reflash")
        self.gridLayout.addWidget(self.pb_Reflash, 3, 0, 1, 1)
        self.MplWidget = MplWidget(parent=From_TechAnalyze)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout.addWidget(self.MplWidget, 2, 1, 2, 1)

        self.retranslateUi(From_TechAnalyze)
        QtCore.QMetaObject.connectSlotsByName(From_TechAnalyze)

    def retranslateUi(self, From_TechAnalyze):
        _translate = QtCore.QCoreApplication.translate
        From_TechAnalyze.setWindowTitle(_translate("From_TechAnalyze", "Form"))
        self.lab_StockID.setText(_translate("From_TechAnalyze", "股票號碼:"))
        self.lab_FromDate.setText(_translate("From_TechAnalyze", "起始日期:"))
        self.de_FromDate.setDisplayFormat(
            _translate("From_TechAnalyze", "yyyy-MM-dd"))
        self.lab_ToDate.setText(_translate("From_TechAnalyze", "最終日期:"))
        self.de_ToDate.setDisplayFormat(
            _translate("From_TechAnalyze", "yyyy-MM-dd"))
        self.pb_Query.setText(_translate("From_TechAnalyze", "查詢"))
        self.pb_Reflash.setText(_translate("From_TechAnalyze", "圖表重新整理"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    From_TechAnalyze = QtWidgets.QWidget()
    ui = Ui_From_TechAnalyze()
    ui.setupUi(From_TechAnalyze)
    From_TechAnalyze.show()
    sys.exit(app.exec())
